// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Bodoni_Moda } from "next/font/google";  // Import Bodoni Moda
import "./globals.css";
import Footer from "@/components/Footer";
import Providers from "./providers";
import HeaderWrapper from "@/components/headerwraper";  // Import HeaderWrapper

const inter = Inter({ subsets: ["latin"] });
const bodoniModa = Bodoni_Moda({ 
  subsets: ['latin'],
  weight: ['400', '700'],  // Add weights you need
  variable: '--font-bodoni-moda',  // Custom CSS variable for Bodoni Moda
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${bodoniModa.variable}`}> {/* Apply both Inter and Bodoni Moda */}
        <Providers>
          <HeaderWrapper /> {/* Use the HeaderWrapper component */}
          {children}
          <Footer /> {/* Always show the Footer */}
        </Providers>
      </body>
    </html>
  );
}
